[tasks.test]
depends = ["fmt"]
run = "cargo test --quiet"

[tasks.clippy]
depends = ["fmt"]
run = "cargo clippy --quiet --all-features --all-targets -- -D warnings"

[tasks.fmt]
run = "cargo fmt"

[tasks.check]
depends = ["test", "clippy"]


[tasks.coverage]
run = [
    "cargo tarpaulin --out Html",
    "echo coverage report generated at tarpaulin-report.html",
]
